import React from 'react';

const Terms = ({ onBack }) => {
    return (
        <div className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8 animate-fade-in">
            <div className="max-w-3xl mx-auto">
                <button
                    onClick={onBack}
                    className="mb-8 flex items-center text-gray-600 hover:text-primary transition-colors duration-200 font-medium"
                >
                    <svg
                        className="w-5 h-5 mr-2"
                        fill="none"
                        stroke="currentColor"
                        viewBox="0 0 24 24"
                    >
                        <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth="2"
                            d="M10 19l-7-7m0 0l7-7m-7 7h18"
                        />
                    </svg>
                    Back to Calculator
                </button>

                <div className="bg-white shadow-lg rounded-2xl p-8 sm:p-12">
                    <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Use</h1>
                    <p className="text-gray-500 mb-8">Effective Date: January 1, 2026</p>

                    <div className="prose prose-slate max-w-none text-gray-800">
                        <p className="mb-6">
                            Welcome to TaxPadi ("we," "us," or "our"). By accessing or using our web application,
                            mobile interface, or AI assistant ("Services"), you agree to be bound by these Terms
                            of Use. If you do not agree to these terms, please do not use our Services.
                        </p>

                        <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">1. Nature of Service (Disclaimer)</h2>
                        <p className="mb-4">
                            TaxPadi is an educational and planning tool, not a professional tax advisory firm.
                        </p>
                        <ul className="list-disc pl-5 space-y-2 mb-6">
                            <li>
                                <strong>Informational Use Only:</strong> The calculations, estimates, and documents
                                generated by TaxPadi are for informational purposes only. They are based on our
                                interpretation of the Nigeria Tax Act 2025 and other relevant fiscal laws.
                            </li>
                            <li>
                                <strong>Not Legal Advice:</strong> Use of this app does not create a client-professional
                                relationship between you and TaxPadi. We are not a substitute for a chartered tax
                                practitioner or financial advisor.
                            </li>
                            <li>
                                <strong>Verification:</strong> You are responsible for verifying all outputs with a certified
                                member of the Chartered Institute of Taxation of Nigeria (CITN) or the relevant tax
                                authority (FIRS/LIRS) before filing any official returns.
                            </li>
                        </ul>

                        <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">2. Accuracy of Calculations</h2>
                        <p className="mb-4">
                            While we strive to ensure our calculator and "Brain" logic reflect the latest 2026 Tax Regime,
                            we do not guarantee 100% accuracy.
                        </p>
                        <ul className="list-disc pl-5 space-y-2 mb-6">
                            <li>Tax laws are subject to interpretation and frequent changes by the Federal Government.</li>
                            <li>We are not liable for any discrepancies, errors, or financial losses resulting from reliance on our calculations.</li>
                        </ul>

                        <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">3. The "Padi" AI Assistant</h2>
                        <p className="mb-4">Our chat feature ("Padi") is powered by Artificial Intelligence.</p>
                        <ul className="list-disc pl-5 space-y-2 mb-6">
                            <li>
                                <strong>Potential Errors:</strong> AI models can occasionally produce incorrect or
                                "hallucinated" information. Always cross-check Padi’s advice against official government publications.
                            </li>
                            <li>
                                <strong>No Liability:</strong> We accept no liability for actions taken based on conversations with the AI agent.
                            </li>
                        </ul>

                        <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">4. Data Privacy & Local Storage</h2>
                        <p className="mb-4">We are a Privacy-First platform.</p>
                        <ul className="list-disc pl-5 space-y-2 mb-6">
                            <li>
                                <strong>No Server Storage:</strong> For this version of the Service, we do not store your
                                Personal Identifiable Information (PII)—such as your Name, Salary, Rent, or Tax
                                Identification Number (TIN)—on our servers.
                            </li>
                            <li>
                                <strong>Local Device:</strong> All financial data you enter is stored locally on your device
                                (in your browser's Local Storage). If you clear your browser cache or lose your device,
                                this data will be lost. We cannot recover it for you.
                            </li>
                            <li>
                                <strong>Usage Tracking:</strong> We use anonymous analytics tools (like PostHog and Vercel Analytics)
                                to track aggregate usage patterns (e.g., "How many people clicked Calculate"). This data does not
                                contain your personal financial details.
                            </li>
                        </ul>

                        <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">5. User Obligations</h2>
                        <p className="mb-2">By using TaxPadi, you agree:</p>
                        <ul className="list-disc pl-5 space-y-2 mb-6">
                            <li>Not to use the platform for fraudulent tax evasion or illegal financial activities.</li>
                            <li>Not to reverse-engineer, scrape, or copy our code, logic, or the "Padi" persona.</li>
                            <li>That you are solely responsible for the accuracy of the data you input into the calculator.</li>
                        </ul>

                        <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">6. Limitation of Liability</h2>
                        <p className="mb-2">
                            To the fullest extent permitted by Nigerian law, TaxPadi and its developers shall not be liable for
                            any direct, indirect, incidental, or consequential damages arising from:
                        </p>
                        <ul className="list-disc pl-5 space-y-2 mb-6">
                            <li>Your use or inability to use the Service.</li>
                            <li>Any errors in tax filing based on our generated documents.</li>
                            <li>Penalties, fines, or interest imposed by tax authorities.</li>
                        </ul>

                        <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">7. Intellectual Property</h2>
                        <p className="mb-6">
                            The design, code, logic, "TaxPadi" name, and logo are the intellectual property of the TaxPadi team.
                            You are granted a limited, non-exclusive, non-transferable license to use the Service for personal,
                            non-commercial use.
                        </p>

                        <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">8. Third-Party Services</h2>
                        <p className="mb-6">
                            Our Service may integrate with third-party tools (e.g., WhatsApp via Twilio, Voice via Vapi.ai).
                            We are not responsible for the availability or privacy practices of these third-party platforms.
                        </p>

                        <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">9. Governing Law</h2>
                        <p className="mb-6">
                            These Terms shall be governed by and construed in accordance with the laws of the Federal Republic of Nigeria.
                            Any disputes arising from these terms shall be subject to the exclusive jurisdiction of the courts in Nigeria.
                        </p>

                        <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">10. Contact Us</h2>
                        <p className="mb-6">
                            For feedback, bug reports, or inquiries, please contact us via the Feedback Widget on our platform or
                            email: <a href="mailto:hello@taxpadi.com" className="text-primary hover:underline">hello@taxpadi.com</a>.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Terms;
